---
title: "day6interactive"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(here)
library(janitor)
```


```{r}
wb_indicators_df <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))

```
```{r}
wb_indicators_long <- wb_indicators_df %>% pivot_longer(
    cols = `2001 [YR2001]`:`2020 [YR2020]`, 
    names_to = 'year', 
    values_to = 'indicator_value'
      )
```

```{r}
wb_indicators_clean <- wb_indicators_long %>% 
  tidyr::separate(col = year, 
                  into = c("year", "year_chr"), 
                  sep = " ") 

wb_indicators_clean2 <- wb_indicators_clean %>%  dplyr::select(-year_chr, -`Country Code`, -`Series Code`) #use select on columns , use separate on rows ? something 

```

```{r}
wb_indicators_tidy <- wb_indicators_clean2 %>% 
  tidyr::drop_na(`Series Name`) %>% 
  tidyr::pivot_wider(names_from = `Series Name`, 
                     values_from = indicator_value) %>%

  dplyr::rename(country = "Country Name", access_fuels_pp = "Access to clean fuels and technologies for cooking (% of population)", access_electricity_pp = "Access to electricity (% of population)" , co2_emissions_kt =  "CO2 emissions (kt)" , fossil_fuel_cons_pt = "Fossil fuel energy consumption (% of total)", water_stress = "Level of water stress: freshwater withdrawal as a proportion of available freshwater resources") %>% 
  dplyr::mutate(year = as.numeric(year))

```
# ```{r}
# names(wb_indicators_tidy) <- c("country", 
#                                "year", 
#                                "access_clean_fuels_pp", 
#                                "access_electricity_pt",
#                                "co2_emissions_kt",
#                                "fossil_fuel_cons_pt",
#                                "water_stress")
# ```
```{r}
ggplot(data = wb_indicators_tidy, aes(x=year, y=co2_emissions_kt))+geom_line(aes(color = country)) + theme(legend.position = "none")
```

